### ISSUE TITLE
Is Ueberauth vulnerable to CVE 2015 9284?

### ISSUE THREAD

**Issue by createdbypete** [ueberauth/ueberauth#125]
Stumbled across this when browsing the Omniauth repo the other day and thought I'd ask here as it seemed quite important.

- https://github.com/omniauth/omniauth/wiki/Resolving-CVE-2015-9284

The above wiki outlines a resolution for Omniauth but there is also links to the CVE and PR (that's been open since 2015, the merging of the resolution seems stalled due to it being a big breaking change?) which I won't link to directly here so it preserves the full context. However, a summary of the vulnerability seems to be:

> The request phase in OmniAuth is currently vulnerable to Cross-Site Request Forgery, which allows an attacker to easily gain full access to a user's account on a site that uses OmniAuth, when used in combination with another CSRF vulnerability on the side of a connected OAuth provider.

Not sure what this means to Ueberauth, if anything, but it felt prudent to raise since I couldn't find any mention of it and Ueberauth.

**Comment by Hanspagh** [comment]
Hi @createdbypete 
Thanks for the link.

I had a quick look at the code base and does in fact look like the request phase is done with a get request.
https://github.com/ueberauth/ueberauth/blob/bfa98c259dc2edd72ef77ac038187e8cf1bc70c5/lib/ueberauth.ex#L339

I will have a closer look one of the following days

**Comment by BobbyMcWho** [comment]
Hello, it does indeed appear that Ueberauth is susceptible to this kind of attack. 

Since the threads and history of that vulnerability are long and old, let me try to sum it up:

We have **MyApp**, an elixir app using Ueberauth.  
We have **ProviderApp**, a 3rd party application that functions as an OAuth Provider.  
We have **D.Victim** who has unfortunately become the target of this attack.  

ProviderApp has a gnarly bug that has allowed an attacker to log in to _their_ ProviderApp account on D.Victim's computer.  

The attacker has also convinced D.Victim to open a website with a cute picture of a cat!

Unfortunately, the page also had a fake image with a resource location of MyApp's login path. 

`<img src="myapp.com/auth/provider_app"/>` 

Because this path is GET and considered a [safe](https://tools.ietf.org/html/rfc7231#section-4.2.1) method by browsers, it's loaded just fine, and the attacker's cookie allowed it to auto attach their account to D.Victim's!

Now, POST requests are _safer_ but not the perfect solution. If your app isn't configured to disallow post requests from external origins, then a similar kind of attack can be done by abusing html forms. 

You must use a POST route, in conjunction with an [authenticity token](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#token-based-mitigation) to verify that the request to the request_path came from your site.

**Comment by BobbyMcWho** [comment]
In a phoenix app, as long as your auth routes are piping through Phoenix's [protect_from_forgery](https://github.com/ueberauth/ueberauth_example/blob/master/lib/ueberauth_example_web/router.ex#L11) plug, you should be able to mitigate this by:
- changing your [get](https://github.com/ueberauth/ueberauth_example/blob/master/lib/ueberauth_example_web/router.ex#L22) route to a post
- changing your [login links](https://github.com/ueberauth/ueberauth_example/blob/master/lib/ueberauth_example_web/templates/page/index.html.eex#L17-L45) to use either 
  - [Phoenix.HTML.Link.link](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Link.html#link/2) (note the [phoenix_html.js](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Link.html#link/2-javascript-dependency) dependency)
  - [Phoenix.HTML.Form.form_for](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html#module-with-limited-data) using the `@conn` as the form object, as by default form_for includes a [csrf_token](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html#module-csrf-protection) hidden input. 

In a non-phoenix Plug app, you will have to implement a custom plug pattern using [Plug.CSRFProtection](https://hexdocs.pm/plug/Plug.CSRFProtection.html) ([here](https://github.com/phoenixframework/phoenix/blob/v1.5.7/lib/phoenix/controller.ex#L1073-L1084)'s Phoenix's implementation of the plug portion), and manually adding `_csrf_token` hidden params to your login forms. Note that you will still also need to change your get route matcher to post as well. 

Regardless, because the default behavior of this library allows for this vulnerability, we should probably submit a CVE and resolve it in a major version bump.

**Comment by Hanspagh** [comment]
Thank you @BobbyMcWho for going into detail with this.

I think it is important to mention this vulnerability is ONLY relevant when the flow of the app is to add an alternate identity to an already logged-in account when signing in with another identity than the currently logged-in one.

So only clients following that flow are vulnerable to this.

I think the biggest issue right now is that the request phase is actually hardcoded to use 'GET', so we can not even configure this for now.

**Comment by BobbyMcWho** [comment]
Right, I just merged some changes into a 2_0 branch of omniauth that will fix the default-vulnerable state by using POST as the only allowed request method by default

**Comment by evadne** [comment]
The workaround if you use Ueberauth  is as follows (tested against 0.6.3)

1. Change stanzas in your router to only have POSTs, e.g. `post "/:provider", AuthController, :request`
2. Change all of your auth views to POST the request (if you use the helper from Phoenix.HTML then CSRF and submission via POST is taken care of) e.g. `link(to: Routes.auth_path(@conn, :request, "google"), method: "POST"`
3. Change your auth controller to have a custom implementation of `request/2`, e.g. `Ueberauth.call(%{conn | method: "GET"}, Ueberauth.init(otp_app: @otp_app))`

IMO the easy fix involves generating both GET and POST routes in [here](https://github.com/ueberauth/ueberauth/blob/1fc1e45e5a5047a0afb56b451171419300d0b7d5/lib/ueberauth.ex#L351) to accommodate the POST usage and avoid users having to implement step 3.

A more involved fix would be to pull in CSRF logic from Phoenix and generate a self-submitting HTML page for step 2 (though this might be in excess of what the maintainers want to maintain)

**Comment by yordis** [comment]
Is this related to https://github.com/ueberauth/ueberauth/pull/136 ?

**Comment by evadne** [comment]
@yordis Hi, thanks. I think it is related and you have solved it in a proper manner by ferrying a token along in Ueberauth while my workaround required Phoenix to do the CSRF work.

**Comment by yordis** [comment]
@evadne should this be considered "fix"? (we still need to release the package and fix the clients)

**Comment by Hanspagh** [comment]
I agree, this should be solved by the clients that now use the CSRF check.
Since no adversary would be able to inject a CSRF token into the session, any unintended loading of get request to `myapp.com/auth/provider_app` would not parse the CSRF check. 

Only get requests generated by the app would have a valid CSRF token. We could argue that an adversary could start a login flow on the victim's PC, but to my knowledge, they would never be able to inject a toke into the same-site cookie.

I am missing anything?
