### ISSUE TITLE
Prevent CSRF Using state Parameter

### ISSUE THREAD

**Issue by jclem** [ueberauth/ueberauth#135]
**Preface**: I am not a security professional. This recommendation is based on my own limited experience implementing the client side of the OAuth 2.0 flow and my research into various implementations. I highly recommend this issue and any subsequent PRs are reviewed by someone that knows more about this than me. 😄

One place where Ueberauth does not currently appear to satisfy the OAuth 2.0 specification is in CSRF protection:

> The client MUST implement CSRF protection for its redirection URI.

\- [*10.12. Cross-Site Request Forgery*](https://tools.ietf.org/html/rfc6749#section-10.12)

Currently, I don't believe Ueberauth provides a solution or a recommendation to its users. The recommendation made by the RFC is to use the `state` parameter:

> This is typically accomplished by requiring any request sent to the
 redirection URI endpoint to include a value that binds the request to
 the user-agent's authenticated state (e.g., a hash of the session
 cookie used to authenticate the user-agent).  The client SHOULD
 utilize the "state" request parameter to deliver this value to the
 authorization server when making an authorization request.

\- [*10.12. Cross-Site Request Forgery*](https://tools.ietf.org/html/rfc6749#section-10.12)

For Ueberauth, I recommend that we do something similar to what OmniAuth does to solve this. Essentially, the process goes like this:

1. Before redirecting a user to the provider login URL, add a cryptographically secure random number to the user's **signed, same-site** session cookie.
2. During the callback phase, verify that the `state` parameter in the callback URL is equal to the value in the user's session.

Not all providers support the `state` parameter (i.e. they ignore it), which is why [OmniAuth provides a :provider_ignores_state configuration value](https://github.com/omniauth/omniauth-oauth2/blob/8438b89b712e03337932a0d95096258c892ea0f3/lib/omniauth/strategies/oauth2.rb#L31).

For reference, here are the relevant places in omniauth-oauth2 where these checks occur:

1. https://github.com/omniauth/omniauth-oauth2/blob/8438b89b712e03337932a0d95096258c892ea0f3/lib/omniauth/strategies/oauth2.rb#L75
2. https://github.com/omniauth/omniauth-oauth2/blob/8438b89b712e03337932a0d95096258c892ea0f3/lib/omniauth/strategies/oauth2.rb#L88

## Open Questions

- Can we assume that there's a signed, same-site session cookie that we can place the state param in, or does Ueberauth need to handle that, which would require adding a signing secret configuration option?
- I'm assuming the signed cookie approach is the easiest way to validate `state`, but is there a better option for Ueberauth?
- For providers that ignore state, how should Ueberauth make sure users are aware that they should implement CSRF protection on their own via some other means? This may be outside the scope of this issue, but what would those other means be?

## Notes

- This does not address CSRF as a result of [CVE-2015-9284](https://github.com/omniauth/omniauth/pull/809); that should be handled separately.

**Comment by yordis** [comment]
Currently, each client will have to deal with this, therefore, the issue will be in particular clients that don't respect such specification.

I am thinking of adding a callback that turns off the validation of such params, so we must add such callback to each strategy.

As of today, clients will have to deal with passing the param in the URL, for example: https://github.com/ueberauth/ueberauth_github/blob/a3bc7032db0cd67c8d65c6b3433d3a8ae645ba71/lib/ueberauth/strategy/github.ex#L100-L101

Since the underline oauth2 package is the one that deals with adding such value to the URL :shru

**Comment by yordis** [comment]
Also, https://github.com/omniauth/omniauth-oauth2/blob/8438b89b712e03337932a0d95096258c892ea0f3/lib/omniauth/strategies/oauth2.rb#L75 seems to use the session for this, although from reading the spec, they recommend cookies.

**Comment by skylerparr** [comment]
Would it be possible to describe to me an example on how to use this when using `xhr`? I've been digging around this PR for a couple of days trying to understand it better and I'm having a hard time groking how this works with `xhr`.

**Comment by AlekKras** [comment]
Pinging @yordis and @Hanspagh on some examples of how to use `xhr` with regards to CSRF ^

**Comment by seungjinRonin** [comment]
Question on this. We need to enable SMART on FHIR OAuth2, and cookies is not what will be used - only the `state` parameter. Would I need to turn off the feature and implement the `state` comparison to be only in the parameters, not cookie? Right now I'm getting `ueberauth_failure` on the callback because cookie doesn't exist with `state` key.

**Comment by Ajwah** [comment]
@yordis @Hanspagh I am currently handling CSRF myself which now with version `0.7` breaks everything. I need to be able to set the state param myself or either disable the CSRF at `config.exs`-level. 

Which solution do you prefer for me to attempt a PR?

**Comment by yordis** [comment]
I would suggest letting Ueberauth handle it unless you have a strong reason against it.

> 0.7 breaks everything

You can always opt-out from it by disabling the CSRF check, which I wouldn't recommend to do

**Comment by Ajwah** [comment]
> You can always opt-out from it by disabling the CSRF check, which I wouldn't recommend to do

Currently this is only possible for someone who is implementing an `UeberAuth.Strategy`. But what about the user of a library, such as `ueberauth_google` etc. ? We have no way to disable `CSRF`-mitigation. The reason why I would like to disable it is because:
1. I already have implemented `CSRF`-mitigation
2. The implementation by this library contradicts certain desired functionality that my application requires.

So in addition to library implementors(e.g. `ueberauth_google` etc.) to be able to opt out of `CSRF`-mitigation by doing: 

```elixir 
use Ueberauth.Strategy, ignores_csrf_attack: true
```

I would like to suggest that application developers(e.g., those using libraries such as `ueberauth_google`) could disable this on a `config.exs`-level.

Alternatively(and this would be better for my use-case IMHO), have a way for us to set the state-param on a `conn` level ourselves and instead of you generating a random value, to use the value we supply.

**Comment by yordis** [comment]
I am not on board with the libraries adding a configuration because some people decided to overwrite how it works.

If the library itself has a bug and/or some security concern, we should address it.

But for this particular case, what is the problem with removing your custom code that supposes to be fixed by this? Is there any problem with the value supplied at the moment?

**Comment by Ajwah** [comment]
My usecase requires I need to have access to that random value before the
oauth flow happens and after the callback has returned.

**Comment by yordis** [comment]
I am sorry, but I can't understand the use case based on that. I don't have any context about the Why and What; that response just let me know the How.

Would you mind sharing more details about the use case, primarily around What and Why?

**Comment by arjan** [comment]
You could indeed use the state parameter to tack application-specific state back into the flow once the user authenticates. However the RFC says you "should" use it for CSRF which is precisely what 0.7 now does. Any other state variables could also go into a cookie or session.

In my [PR for the Facebook strategy](https://github.com/ueberauth/ueberauth_facebook/pull/65) I faced with this exact issue as well, I removed the option for providing a custom state parameter while adding support for 0.7.

Maybe it would indeed be good to make Ueberauth's handling of the `state` parameter configurable on the application level, per stategy:

```
config :ueberauth, Ueberauth.Strategy.Facebook.OAuth, ignores_csrf_attack: true
```

Instead of hardcoding it now in the strategy's `use` clause.

**Comment by yordis** [comment]
@arjan the reason we let people even configure that today is to avoid having to have breaking changes (obviously breaking changes from our perspective because some people did the right thing, I am sorry)

But this is not one of those things that we should let people disable, if some people feel strongly about it, then I would suggest creating your own custom implementation of a provider.

I hope you understand thou, security is hard, and leaving the ownership to people to do the right thing is something that always goes wrong, power-users are already power-users so they have no problem in taking ownership.

**Comment by arjan** [comment]
Yes I fully agree actually, it's just that in that particular PR I removed the ability to pass the state parameter, which is fine by me but it was also explicitly mentioned in the readme (removed that section as well) so I was just wondering whether I maybe did miss a use case.

**Comment by yordis** [comment]
Right right, having a multi-repo is hard to maintain over time, I am trying to clean things one repo at the time; doing what I can.
